"""Enum constants"""

from enum import Enum
from typing import NamedTuple


class PaymentForm(Enum):
    """SAT's payment form codes"""

    EFECTIVO = "01"
    CHEQUE_NOMINATIVO = "02"
    TRANSFERENCIA_ELECTRONICA_DE_FONDOS = "03"
    TARJETA_DE_CREDITO = "04"
    MONEDERO_ELECTRONICO = "05"
    DINERO_ELECTRONICO = "06"
    VALES_DE_DESPENSA = "08"
    DACION_EN_PAGO = "12"
    PAGO_POR_SUBROGACION = "13"
    PAGO_POR_CONSIGNACION = "14"
    CONDONACION = "15"
    COMPENSACION = "17"
    NOVACION = "23"
    CONFUSION = "24"
    REMISION_DE_DEUDA = "25"
    PRESCRIPCION_O_CADUCIDAD = "26"
    A_SATISFACCION_DEL_ACREEDOR = "27"
    TARJETA_DE_DEBITO = "28"
    TARJETA_DE_SERVICIOS = "29"
    APLICACION_DE_ANTICIPOS = "30"
    INTERMEDIARIO_PAGOS = "31"
    POR_DEFINIR = "99"


class PaymentMethod(Enum):
    """SAT's payment method"""

    UNA_SOLA_EXHIBICION = "PUE"
    PARCIALIDADES_DIFERIDO = "PPD"


class InvoiceUse(Enum):
    """SAT's CFDI usage"""

    ADQUISICION_MERCANCIAS = "G01"
    DEVOLUCIONES_DESCUENTOS_BONIFICACIONES = "G02"
    GASTOS_EN_GENERAL = "G03"
    CONSTRUCCIONES = "I01"
    MOBILIARIO_Y_EQUIPO_DE_OFICINA = "I02"
    EQUIPO_DE_TRANSPORTE = "I03"
    EQUIPO_DE_COMPUTO = "I04"
    DADOS_TROQUELES_HERRAMENTAL = "I05"
    COMUNICACIONES_TELEFONICAS = "I06"
    COMUNICACIONES_SATELITALES = "I07"
    OTRA_MAQUINARIA = "I08"
    HONORARIOS_MEDICOS = "D01"
    GASTOS_MEDICOS_POR_INCAPACIDAD = "D02"
    GASTOS_FUNERALES = "D03"
    DONATIVOS = "D04"
    INTERESES_POR_CREDITOS_HIPOTECARIOS = "D05"
    APORTACIONES_VOLUNTARIAS_SAR = "D06"
    PRIMA_SEGUROS_GASTOS_MEDICOS = "D07"
    GASTOS_TRANSPORTACION_ESCOLAR = "D08"
    CUENTAS_AHORRO_PENSIONES = "D09"
    SERVICIOS_EDUCATIVOS = "D10"
    SIN_EFECTOS_FISCALES = "S01"
    PAGOS = "CP01"
    NOMINA = "CN01"


class InvoiceRelation(Enum):
    """SAT's Invoice Relation"""

    NOTA_DE_CREDITO = "01"
    NOTA_DE_DEBITO = "02"
    DELOVUCION_DE_MERCANCIA = "03"
    SUSTITUCION_DE_CFDI_PREVIOS = "04"
    TRASLADOS_DE_MERCANCIA_FACTURADOS_PREVIAMENTE = "05"
    FACTURA_POR_TRASLADOS_PREVIOS = "06"
    APLICACION_DE_ANTICIPO = "07"
    FACTURA_POR_PAGOS_PARCIALIDADES = "08"
    FACTURA_POR_PAGOS_DIFERIDOS = "09"


class TaxSystem(Enum):
    """SAT's Tax System (Fiscal Regime)"""

    GENERAL_LEY_DE_PERSONAS_MORALES = "601"
    PERSONAS_MORALES_CON_FINES_NO_LUCRATIVOS = "603"
    SUELDOS_Y_SALARIOS = "605"
    ARRENDAMIENTO = "606"
    ENAJENACION_ADQUISICION_DE_BIENES = "607"
    DEMAS_INGRESOS = "608"
    RESIDENTES_EN_EL_EXTRANJERO = "610"
    INGRESOS_POR_DIVIDENDOS = "611"
    PERSONAS_FISICAS_CON_ACTIVIDADES_EMPRESARIALES_Y_PROFESIONALES = "612"
    INGRESOS_POR_INTERESES = "614"
    SIN_OBLIGACIONES_FISCALES = "616"
    SOCIEDADES_COOPERATIVAS_DE_PRODUCCION = "620"
    INCORPORACION_FISCAL = "621"
    ACTIVIDADES_AGRICOLAS_GANADERAS_SILVICOLAS_Y_PESQUERAS = "622"
    OPCIONAL_PARA_GRUPOS_DE_SOCIEDADES = "623"
    COORDINADOS = "624"
    ACTIVIDADES_EMPRESARIALES_CON_INGRESOS_A_TRAVES_DE_PLATAFORMAS_TECNOLOGICAS = "625"
    REGIMEN_SIMPLIFICADO_DE_CONFIANZA = "626"
    HIDROCARBUROS = "628"
    REGIMENES_FISCALES_PREFERENTES_EMPRESAS_MULTINACIONALES = "629"
    ENAJENACION_ACCIONES_EN_BOLSA_DE_VALORES = "630"


class Month(Enum):
    """Months and bimonths"""

    ENERO = "01"
    FEBRERO = "02"
    MARZO = "03"
    ABRIL = "04"
    MAYO = "05"
    JUNIO = "06"
    JULIO = "07"
    AGOSTO = "08"
    SEPTIEMBRE = "09"
    OCTUBRE = "10"
    NOVIEMBRE = "11"
    DICIEMBRE = "12"
    ENERO_FEBRERO = "13"
    MARZO_ABRIL = "14"
    MAYO_JUNIO = "15"
    JULIO_AGOSTO = "16"
    SEPTIEMBRE_OCTUBRE = "17"
    NOVIEMBRE_DICIEMBRE = "18"


class ContractType(Enum):
    """SAT's Contract type"""

    TRABAJO_POR_TIEMPO_INDETERMINADO = "01"
    TRABAJO_PARA_OBRA_DETERMINADA = "02"
    TRABAJO_POR_TIEMPO_DETERMINADO = "03"
    TRABAJO_POR_TEMPORADA = "04"
    TRABAJO_SUJETO_A_PRUEBA = "05"
    TRABAJO_CON_CAPACITACION_INICIAL = "06"
    POR_PAGO_DE_HORA_LABORADA = "07"
    TRABAJO_POR_COMISION_LABORAL = "08"
    DONDE_NO_EXISTE_RELACION_DE_TRABAJO = "09"
    JUBILACION_PENSION_RETIRO = "10"
    OTRO_CONTRATO = "99"


class WorkingDayType(Enum):
    """SAT's Work day type"""

    DIURNA = "01"
    NOCTURNA = "02"
    MIXTA = "03"
    POR_HORA = "04"
    REDUCIDA = "05"
    CONTINUADA = "06"
    PARTIDA = "07"
    POR_TURNOS = "08"
    OTRA_JORNADA = "99"


class CancellationReason(Enum):
    ERRORS_WITH_RELATION = "01"
    ERRORS_WITHOUT_RELATION = "02"
    OPERATION_NOT_CARRIED_OUT = "03"
    NOMINATIVE_TRANSACTION = "04"


class ReceiptPeriodicity(Enum):
    DAY = "day"
    WEEK = "week"
    FORTNIGHT = "fortnight"
    MONTH = "month"
    TWO_MONTHS = "two_months"


class Catalogs(NamedTuple):
    payment_forms = PaymentForm
    payment_methods = PaymentMethod
    invoice_use = InvoiceUse
    invoice_relations = InvoiceRelation
    tax_systtems = TaxSystem
    months = Month
    contracts = ContractType
    working_days = WorkingDayType
    cancellation_reasons = CancellationReason

    receipt_periodicity = ReceiptPeriodicity
